paths:
  data: data
  static: static
  uploads: static/images
  assets: assets
  content: content
  pages: content

collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    description: ""
    icon: laptop_mac
    _enabled_editors:
      - visual
    schemas:
      default:
        name: New Page
        path: .cloudcannon/schemas/page.md
        remove_extra_inputs: false
  data:
    path: data
    output: false
    description: ""
    icon: analytics
    _inputs:
      value:
        type: color

data_config:
  colors: true

_inputs:
  background_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name

source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true

timezone: Etc/UTC

generator:
  metadata:
    markdown: goldmark
    goldmark:
      renderer:
        hardWraps: true
