paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads
  source: ''
  archetypes: archetypes
  assets: assets
  content: content
  pages: content
  publish: public
  config: ''
collections_config:
  pages:
    path: content
    output: true
    filter: strict
    parse_branch_index: true
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
  data:
    path: data
    output: false
    description: ''
    icon: notes
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
_editables:
  content:
    allow_custom_markup: true
    remove_custom_markup: false
    blockquote:
    bold:
    bulletedlist:
    center:
    code:
    copyformatting:
    correct_orientation:
    embed:
    expandable:
    format:
    height:
    horizontalrule:
    image:
    image_size_attributes: true
    indent:
    italic:
    justify:
    left:
    link:
    mime_type:
    numberedlist:
    outdent:
    paths:
    redo:
    removeformat:
    resize_style: contain
    right:
    snippet:
    strike:
    styles:
    subscript:
    superscript:
    table:
    underline:
    undo:
    width:
data_config: {}
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Etc/UTC
