paths:
  static: static
  uploads: static/images

collections_config:
  pages:
    path: content
    url: '[full_slug]'
    icon: laptop_mac
    _enabled_editors:
      - visual
    schemas:
      default:
        name: New Page
        path: .cloudcannon/schemas/page.md
        remove_extra_inputs: false
  data:
    path: data
    disable_url: true
    icon: analytics
    _inputs:
      value:
        type: color

data_config:
  colors:
    path: data/colors.yml

_inputs:
  background_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  text_color:
    type: select
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name

source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true

timezone: Etc/UTC
