# Metadata about this component, to be used in the CMS
spec:
  structures:
    - hero_blocks
  label: "Hero - Video Background"
  description: Text over video bg
  icon: duo
  tags:
    - Heading
    - Video
    - Buttons

# Defines the structure of this component, as well as the default values
blueprint:
  heading:
    heading_text: 
    text_color: '#ffffff'
  subheading:
    text_content: 
    text_color: '#ffffff'
  video:
    video_path: /videos/nz-coast.mp4
    poster_image: /images/nz-coast-poster.png
  header_style_overrides:
    background_color: transparent
    text_color: '#ffffff'
    hover_text_color: '#F1F1F1'
    alternate_logo: /images/logos/logo-wordmark-white.png
  background_filters:
    brightness: 0.5
    blur: 1
  buttons:
    - _bookshop_name: buttons/primary
      button_text: 
      button_icon: 
      button_link: 
      background_color: '#034ad8'
      hover_brightness: 0.85
      text_color: '#ffffff'

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  header_style_overrides:
    type: object
    comment: Specify header styles for just this page if set. Will not take effect until the next site save & build.
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  hover_text_color:
    type: select
    comment: Updates the header hover text color for this page if set.
    options:
      values: data.colors
      value_key: value
      preview:
        text:
          - key: name
  background_filters:
    type: object
    comment: Set brightness and blur filters over the background video to make the text content more legible.
    options:
      preview:
        icon: exposure
  brightness:
    type: range
    options:
      min: 0
      max: 2
      step: 0.025
  blur:
    type: range
    options:
      min: 0
      max: 10
      step: 0.25
  buttons:
    type: array
    options:
      structures: _structures.buttons
  heading:
    options:
      preview:
        icon: 'short_text'
        text:
          - key: heading_text
          - Heading
        subtext:
          - 'Update heading text and color'
  subheading:
    options:
      preview:
        icon: 'description'
  video:
    options:
      preview:
        icon: 'duo'
        text:
          - 'Background Video'
        subtext:
          - key: video_path
          - 'Select a video'
  video_path:
    type: file
    options:
      paths:
        static: static
        uploads: 'static/videos'
  poster_image:
    type: image
    comment: Specifies an image to be shown while the video is downloading.