# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Left-Right Block
  description: Left-Right block with heading, text & button next to image.
  icon: "chrome_reader_mode"
  tags:
    - Image
    - Text
    - Button

# Defines the structure of this component, as well as the default values
blueprint:
  background_color: "#ffffff"
  flipped: true
  heading:
    heading_text: 
    text_color: "#393939"
  text:
    text_content:
    text_color: "#393939"
  image:
    image_path: 
    alt_text: 
  button: bookshop:structure:buttons

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
